services:
  qdrant:
    image: qdrant/qdrant:latest

    container_name: qdrant

    ports:
      - "7000:6333"

    volumes:
      - qdrant_storage:/qdrant/storage

    restart: unless-stopped

volumes:
  qdrant_storage: